; Configuration defaults for ROExt.
; All settings except CodePage use 0 for disable and 1 for enable.
[ROExt]

; Release CPU when RO window is inactive.
; Positive numbers > 1 - custom throttle interval in ms.
AutoFreeCPU = 4

; Minimize RO window on Ctrl+W.
MinimizeKey = 0

; Remap 3-5'th mouse buttons to F24-F22
; Allow binding skills to them.
RemapMouseButtons = 0

; Remap closing RO from Alt+F4 to Alt+PrintScreen.
; Allow using Alt+F4 in game as regular key.
RemapAltF4 = 0

; Make RO window be always on top.
WindowOnTop = 0

; Remove RO window borders and lock its position.
; Change default window size to cover all screen except task bar.
WindowLock = 1

; Override RO window position and size.
; Ignored if WindowWidth = 0 or WindowHeight = 0.
WindowPosX = 0
WindowPosY = 0
WindowWidth = 1600
WindowHeight = 863

; Override codepage used by client, use -1 for no override.
; 65001 (UTF-8) makes client work with all languages at the same time.
; Don't change until you really know what you are doing.
CodePage = -1
