// --------------------------------------------------------------
// - Warning!! Acktung!! Awas!! gevaar!! peligro!! !    -
// --------------------------------------------------------------
// - All scripts here should be used at your own risk. If you   -
// - have edited it yourself, we are not responsible for any    -
// - Damages or whatsoever. Do not report any bugs unless you   -
// - are sure they exist. Please provide evidence and proof.    -
// - eAthena developers are not responsible for any damages or  -
// - disruptions of service during the service of the server    -
// - caused by the included scripts or for any damages          -
// - resulting in the use of the scripts.                       -
// - Thanks,                                                    -
// - eAthena Dev Team                                           -
// --------------------------------------------------------------
// --------------------------------------------------------------
// -                      Monster  Scripts                      -
// --------------------------------------------------------------
//npc: npc/mobs_uaro/citycleaners.txt
//npc: npc/mobs_uaro/pvp.txt
//npc: npc/mobs_uaro/airplane.txt

npc: npc/mobs_uaro/fields/amatsu.txt
npc: npc/mobs_uaro/fields/ayothaya.txt
npc: npc/mobs_uaro/fields/comodo.txt
npc: npc/mobs_uaro/fields/einbroch.txt
npc: npc/mobs_uaro/fields/geffen.txt
npc: npc/mobs_uaro/fields/gonryun.txt
npc: npc/mobs_uaro/fields/hugel.txt
npc: npc/mobs_uaro/fields/jawaii.txt
npc: npc/mobs_uaro/fields/lighthalzen.txt
npc: npc/mobs_uaro/fields/louyang.txt
npc: npc/mobs_uaro/fields/lutie.txt
npc: npc/mobs_uaro/fields/mjolnir.txt
npc: npc/mobs_uaro/fields/morocc.txt
npc: npc/mobs_uaro/fields/niflheim.txt
npc: npc/mobs_uaro/fields/odin.txt
npc: npc/mobs_uaro/fields/payon.txt
npc: npc/mobs_uaro/fields/prontera.txt
npc: npc/mobs_uaro/fields/rachel.txt
npc: npc/mobs_uaro/fields/umbala.txt
npc: npc/mobs_uaro/fields/yuno.txt

npc: npc/mobs_uaro/dungeons/amatdun.txt
npc: npc/mobs_uaro/dungeons/anthell.txt
npc: npc/mobs_uaro/dungeons/ayodun.txt
npc: npc/mobs_uaro/dungeons/abyss.txt
npc: npc/mobs_uaro/dungeons/beachdun.txt
npc: npc/mobs_uaro/dungeons/byalan.txt
npc: npc/mobs_uaro/dungeons/clocktower.txt
npc: npc/mobs_uaro/dungeons/coalmine.txt
npc: npc/mobs_uaro/dungeons/eindun.txt
npc: npc/mobs_uaro/dungeons/gefenia.txt
npc: npc/mobs_uaro/dungeons/geftower.txt
npc: npc/mobs_uaro/dungeons/glastheim.txt
npc: npc/mobs_uaro/dungeons/gondun.txt
npc: npc/mobs_uaro/dungeons/guilddun.txt
npc: npc/mobs_uaro/dungeons/icedun.txt
npc: npc/mobs_uaro/dungeons/jupedun.txt
npc: npc/mobs_uaro/dungeons/kiel.txt
npc: npc/mobs_uaro/dungeons/lhzdun.txt
npc: npc/mobs_uaro/dungeons/louydun.txt
npc: npc/mobs_uaro/dungeons/magmadun.txt
npc: npc/mobs_uaro/dungeons/moc_pyramid.txt
npc: npc/mobs_uaro/dungeons/moc_sphinx.txt
npc: npc/mobs_uaro/dungeons/orcdun.txt
npc: npc/mobs_uaro/dungeons/payoncave.txt
npc: npc/mobs_uaro/dungeons/pront_maze.txt
npc: npc/mobs_uaro/dungeons/pront_sewers.txt
npc: npc/mobs_uaro/dungeons/racheldun.txt
npc: npc/mobs_uaro/dungeons/sunkenship.txt
npc: npc/mobs_uaro/dungeons/thanatos.txt
npc: npc/mobs_uaro/dungeons/toyfactory.txt
npc: npc/mobs_uaro/dungeons/turtleisland.txt
npc: npc/mobs_uaro/dungeons/umbaladun.txt
npc: npc/mobs_uaro/dungeons/yggdrasil.txt
// --------------------------------------------------------------
npc: npc/mobs_uaro/dungeons/clocktower_uaro.txt
